### ISSUE TITLE
whats up with the Timings file?

### ISSUE THREAD

**Issue by charles-fox** [HaMM4R/SightRead#10]
I pulled and tried on run on my Ubuntu machine today.

It barfed because nothing was loaded into the beatPositions array from the timings file.

I tweaked the code (in my fork) to read correctly.

Then it runs; but the beats in the game aren't lined up with the beats in the audio any more.

It also looks like the Timings file is being overwritten.

Please can we have a clealy labelled sidecar file such as QueenTearItUp.mp3.beats , and make sure it does not get overwritten?

Or maybe I am misunderstanding something.

Have a look at my fork if you like, to see how I made it run on my machine.

**Comment by HaMM4R** [comment]
I modified the read code to support the saving of previous scores but seemingly caused some problems so have reverted. 

The beats in the file were for 90bpm but the game is set to 60 hence might look like they don't line up. 

I'm having some issues with performance and as a result the music can desync with the game. I've offloaded the audio processing to the android media player on the device but am unsure what could be causing the bad performance when so few graphics operations are occuring, some help with this problem would be greatly appreciated (though I did fix the file not loading correctly on mobile)
